export const figmaFallbackAssets = {
    heroBanner: '/figma-fallback/hero-banner.svg',
    dishCollage: '/figma-fallback/dish-collage.svg',
    storeImage: '/figma-fallback/store-image.svg',
    avatarSmall: '/figma-fallback/avatar-small.svg',
    reviewerAvatarA: '/figma-fallback/reviewer-avatar-a.svg',
    reviewerAvatarB: '/figma-fallback/reviewer-avatar-b.svg',
    feedDishImage: '/figma-fallback/feed-dish.svg',
    menuItemImage: '/figma-fallback/menu-item.svg',
    ratingStars: '/figma-fallback/rating-stars.svg',
    filterChevron: '/figma-fallback/filter-chevron.svg',
    reactionsLeft: '/figma-fallback/reactions-left.svg',
    reactionsRight: '/figma-fallback/reactions-right.svg',
    starIcon: '/figma-fallback/star-icon.svg',
    tagIcon: '/figma-fallback/tag-icon.svg',
    likeIcon: '/figma-fallback/like-icon.svg',
    commentIcon: '/figma-fallback/comment-icon.svg',
    ratingBadge: '/figma-fallback/rating-badge.svg',
    topReviewerIcon: '/figma-fallback/top-reviewer-icon.svg',
} as const;
