import { CuaHangEntity } from "../../Api/Admin/entities/cua-hang.entity";
import { DonHangChiTietEntity } from "../../Api/Admin/entities/don-hang-chi-tiet.entity";
import { DonHangEntity } from "../../Api/Admin/entities/don-hang.entity";
import { LichSuDonHangEntity } from "../../Api/Admin/entities/lich-su-don-hang.entity";
import { MonAnEntity } from "../../Api/Admin/entities/mon-an.entity";
import type { DeepPartial } from "typeorm";
import { getUserId, type SeederContext } from "./context";

export async function seedDonHang(context: SeederContext) {
  const cuaHangRepo = context.dataSource.getRepository(CuaHangEntity);
  const monAnRepo = context.dataSource.getRepository(MonAnEntity);
  const donHangRepo = context.dataSource.getRepository(DonHangEntity);
  const chiTietRepo = context.dataSource.getRepository(DonHangChiTietEntity);
  const lichSuRepo = context.dataSource.getRepository(LichSuDonHangEntity);

  const maDonHangSeeds = [
    "DH2026041101",
    "DH2026041102",
    "DH2026041003",
    "DH2026040804",
    "DH2026040707",
    "DH2026040608",
    "DH2026032505",
    "DH2026032006",
  ];

  const existingOrders = await donHangRepo.find({
    where: maDonHangSeeds.map((ma) => ({ ma_don_hang: ma })),
  });
  const existingIds = existingOrders.map((item) => item.id);

  if (existingIds.length > 0) {
    await lichSuRepo
      .createQueryBuilder()
      .delete()
      .where("id_don_hang IN (:...ids)", { ids: existingIds })
      .execute();
    await chiTietRepo
      .createQueryBuilder()
      .delete()
      .where("id_don_hang IN (:...ids)", { ids: existingIds })
      .execute();
    await donHangRepo.delete(existingIds);
  }

  await monAnRepo.delete([702]);
  await cuaHangRepo.delete([602]);

  const cuaHang2 = await cuaHangRepo.save({
    id: 602,
    id_chu_so_huu: getUserId(context, "multi@dishnet.vn")!,
    ten_cua_hang: "Cơm Tấm Sài Gòn",
    slug: "com-tam-sai-gon-seed",
    mo_ta: "Quán cơm tấm chuyên phục vụ bữa trưa và tối.",
    anh_dai_dien:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=640&q=80",
    dia_chi_kinh_doanh: "88 Nguyễn Tri Phương, Quận 10, TP.HCM",
    trang_thai_hoat_dong: "hoat_dong",
  });

  await cuaHangRepo.update(cuaHang2.id, {
    anh_dai_dien:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=640&q=80",
  });

  await monAnRepo.save({
    id: 702,
    id_cua_hang: cuaHang2.id,
    ma_mon: "CT001",
    ten_mon: "Cơm tấm sườn bì chả",
    mo_ta: "Phần cơm tấm đầy đủ sườn, bì, chả.",
    hinh_anh_dai_dien:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=640&q=80",
    gia_ban: 65000,
    trang_thai_ban: "dang_ban",
  });

  const orderSeeds: DeepPartial<DonHangEntity>[] = [
    {
      ma_don_hang: "DH2026041101",
      id_nguoi_mua: getUserId(context, "user@dishnet.vn")!,
      id_cua_hang: context.objectIds.get("cua_hang_seed")!,
      nguoi_nhan: "Nguyễn Văn A",
      so_dien_thoai_nhan: "0901234567",
      dia_chi_giao: "40 Nguyễn Như Hạnh, Đà Nẵng",
      nguon_don_hang: "truc_tiep",
      phuong_thuc_thanh_toan: "tien_mat",
      trang_thai_don_hang: "cho_xac_nhan",
      tam_tinh: 118000,
      phi_van_chuyen: 15000,
      tong_giam_gia: 10000,
      tong_thanh_toan: 123000,
      thu_nhap_cua_hang: 103000,
      hoa_hong_nen_tang: 20000,
      hoa_hong_nha_sang_tao: 0,
      thoi_gian_dat: new Date("2026-04-11T09:15:00"),
    },
    {
      ma_don_hang: "DH2026041102",
      id_nguoi_mua: getUserId(context, "creator@dishnet.vn")!,
      id_cua_hang: 602,
      nguoi_nhan: "Khoa Pug TV",
      so_dien_thoai_nhan: "0911222333",
      dia_chi_giao: "21 Trường Chinh, TP.HCM",
      nguon_don_hang: "tim_kiem",
      phuong_thuc_thanh_toan: "vnpay",
      trang_thai_don_hang: "dang_chuan_bi",
      tam_tinh: 130000,
      phi_van_chuyen: 18000,
      tong_giam_gia: 0,
      tong_thanh_toan: 148000,
      thu_nhap_cua_hang: 122000,
      hoa_hong_nen_tang: 26000,
      hoa_hong_nha_sang_tao: 0,
      thoi_gian_dat: new Date("2026-04-11T10:05:00"),
      thoi_gian_xac_nhan: new Date("2026-04-11T10:08:00"),
    },
    {
      ma_don_hang: "DH2026041003",
      id_nguoi_mua: getUserId(context, "store@dishnet.vn")!,
      id_cua_hang: context.objectIds.get("cua_hang_seed")!,
      nguoi_nhan: "Nét Huế - Hàng Bông",
      so_dien_thoai_nhan: "0933444555",
      dia_chi_giao: "12 Hàng Bông, Hoàn Kiếm, Hà Nội",
      nguon_don_hang: "khuyen_mai",
      phuong_thuc_thanh_toan: "vi_dien_tu",
      trang_thai_don_hang: "dang_giao",
      tam_tinh: 59000,
      phi_van_chuyen: 12000,
      tong_giam_gia: 15000,
      tong_thanh_toan: 56000,
      thu_nhap_cua_hang: 45000,
      hoa_hong_nen_tang: 11000,
      hoa_hong_nha_sang_tao: 0,
      thoi_gian_dat: new Date("2026-04-10T19:20:00"),
      thoi_gian_xac_nhan: new Date("2026-04-10T19:25:00"),
      thoi_gian_giao: new Date("2026-04-10T19:45:00"),
    },
    {
      ma_don_hang: "DH2026040804",
      id_nguoi_mua: getUserId(context, "multi@dishnet.vn")!,
      id_cua_hang: 602,
      nguoi_nhan: "Vừa Review Vừa Bán Đồ Ăn",
      so_dien_thoai_nhan: "0944555666",
      dia_chi_giao: "88 Nguyễn Tri Phương, Quận 10, TP.HCM",
      nguon_don_hang: "bai_viet",
      id_bai_viet_nguon: context.objectIds.get("bai_viet_seed")!,
      id_nha_sang_tao_nguon: getUserId(context, "creator@dishnet.vn")!,
      phuong_thuc_thanh_toan: "the",
      trang_thai_don_hang: "da_giao",
      tam_tinh: 195000,
      phi_van_chuyen: 25000,
      tong_giam_gia: 30000,
      tong_thanh_toan: 190000,
      thu_nhap_cua_hang: 160000,
      hoa_hong_nen_tang: 25000,
      hoa_hong_nha_sang_tao: 5000,
      thoi_gian_dat: new Date("2026-04-08T12:10:00"),
      thoi_gian_xac_nhan: new Date("2026-04-08T12:15:00"),
      thoi_gian_giao: new Date("2026-04-08T12:45:00"),
      thoi_gian_hoan_tat: new Date("2026-04-08T13:05:00"),
    },
    {
      ma_don_hang: "DH2026040707",
      id_nguoi_mua: getUserId(context, "user@dishnet.vn")!,
      id_cua_hang: context.objectIds.get("cua_hang_seed")!,
      nguoi_nhan: "Nguyễn Văn A",
      so_dien_thoai_nhan: "0901234567",
      dia_chi_giao: "15 Phan Châu Trinh, Hải Châu, Đà Nẵng",
      nguon_don_hang: "khuyen_mai",
      phuong_thuc_thanh_toan: "vi_dien_tu",
      trang_thai_don_hang: "da_giao",
      tam_tinh: 118000,
      phi_van_chuyen: 12000,
      tong_giam_gia: 30000,
      tong_thanh_toan: 100000,
      thu_nhap_cua_hang: 82000,
      hoa_hong_nen_tang: 18000,
      hoa_hong_nha_sang_tao: 0,
      thoi_gian_dat: new Date("2026-04-07T11:00:00"),
      thoi_gian_xac_nhan: new Date("2026-04-07T11:06:00"),
      thoi_gian_giao: new Date("2026-04-07T11:35:00"),
      thoi_gian_hoan_tat: new Date("2026-04-07T11:50:00"),
    },
    {
      ma_don_hang: "DH2026040608",
      id_nguoi_mua: getUserId(context, "creator@dishnet.vn")!,
      id_cua_hang: 602,
      nguoi_nhan: "Khoa Pug TV",
      so_dien_thoai_nhan: "0911222333",
      dia_chi_giao: "21 Trường Chinh, TP.HCM",
      nguon_don_hang: "tim_kiem",
      phuong_thuc_thanh_toan: "vnpay",
      trang_thai_don_hang: "da_giao",
      tam_tinh: 130000,
      phi_van_chuyen: 15000,
      tong_giam_gia: 5000,
      tong_thanh_toan: 140000,
      thu_nhap_cua_hang: 114000,
      hoa_hong_nen_tang: 26000,
      hoa_hong_nha_sang_tao: 0,
      thoi_gian_dat: new Date("2026-04-06T18:10:00"),
      thoi_gian_xac_nhan: new Date("2026-04-06T18:15:00"),
      thoi_gian_giao: new Date("2026-04-06T18:45:00"),
      thoi_gian_hoan_tat: new Date("2026-04-06T19:00:00"),
    },
    {
      ma_don_hang: "DH2026032505",
      id_nguoi_mua: getUserId(context, "user@dishnet.vn")!,
      id_cua_hang: 602,
      nguoi_nhan: "Nguyễn Văn A",
      so_dien_thoai_nhan: "0901234567",
      dia_chi_giao: "101 Lê Duẩn, Hải Châu, Đà Nẵng",
      nguon_don_hang: "truc_tiep",
      phuong_thuc_thanh_toan: "tien_mat",
      trang_thai_don_hang: "da_huy",
      tam_tinh: 65000,
      phi_van_chuyen: 10000,
      tong_giam_gia: 0,
      tong_thanh_toan: 75000,
      thu_nhap_cua_hang: 0,
      hoa_hong_nen_tang: 0,
      hoa_hong_nha_sang_tao: 0,
      ly_do_huy: "Khách hàng thay đổi địa chỉ giao hàng",
      nguoi_huy: "nguoi_mua",
      thoi_gian_dat: new Date("2026-03-25T08:40:00"),
      thoi_gian_huy: new Date("2026-03-25T08:55:00"),
    },
    {
      ma_don_hang: "DH2026032006",
      id_nguoi_mua: getUserId(context, "locked@dishnet.vn")!,
      id_cua_hang: context.objectIds.get("cua_hang_seed")!,
      nguoi_nhan: "Kẻ Gây Rối",
      so_dien_thoai_nhan: "0966777888",
      dia_chi_giao: "55 Tôn Đức Thắng, Đống Đa, Hà Nội",
      nguon_don_hang: "khuyen_mai",
      phuong_thuc_thanh_toan: "vnpay",
      trang_thai_don_hang: "tra_hang",
      tam_tinh: 118000,
      phi_van_chuyen: 18000,
      tong_giam_gia: 20000,
      tong_thanh_toan: 116000,
      thu_nhap_cua_hang: 0,
      hoa_hong_nen_tang: 0,
      hoa_hong_nha_sang_tao: 0,
      ly_do_tra_hang: "Món ăn giao sai so với đơn đã đặt",
      thoi_gian_dat: new Date("2026-03-20T18:30:00"),
      thoi_gian_xac_nhan: new Date("2026-03-20T18:35:00"),
      thoi_gian_giao: new Date("2026-03-20T19:00:00"),
      thoi_gian_hoan_tat: new Date("2026-03-20T19:25:00"),
    },
  ];

  const orders = await donHangRepo.save(orderSeeds);

  const orderByCode = new Map(orders.map((item) => [item.ma_don_hang, item]));

  await chiTietRepo.save([
    {
      id_don_hang: orderByCode.get("DH2026041101")!.id,
      id_mon_an: context.objectIds.get("mon_an_seed")!,
      ten_mon_snapshot: "Bún bò đặc biệt",
      hinh_anh_snapshot: null,
      don_gia: 59000,
      so_luong: 2,
      thanh_tien: 118000,
      topping_snapshot: JSON.stringify([
        { ten: "Thêm rau muống", gia: 5000, so_luong: 1 },
        { ten: "Thêm chả", gia: 8000, so_luong: 1 },
      ]),
      ghi_chu: "Ít cay",
    },
    {
      id_don_hang: orderByCode.get("DH2026041102")!.id,
      id_mon_an: 702,
      ten_mon_snapshot: "Cơm tấm sườn bì chả",
      hinh_anh_snapshot: null,
      don_gia: 65000,
      so_luong: 2,
      thanh_tien: 130000,
      topping_snapshot: JSON.stringify([
        { ten: "Trứng ốp la", gia: 10000, so_luong: 1 },
        { ten: "Thêm thịt", gia: 15000, so_luong: 1 },
      ]),
      ghi_chu: "Thêm trứng ốp la",
    },
    {
      id_don_hang: orderByCode.get("DH2026041003")!.id,
      id_mon_an: context.objectIds.get("mon_an_seed")!,
      ten_mon_snapshot: "Bún bò đặc biệt",
      hinh_anh_snapshot: null,
      don_gia: 59000,
      so_luong: 1,
      thanh_tien: 59000,
      topping_snapshot: null,
      ghi_chu: null,
    },
    {
      id_don_hang: orderByCode.get("DH2026040804")!.id,
      id_mon_an: 702,
      ten_mon_snapshot: "Cơm tấm sườn bì chả",
      hinh_anh_snapshot: null,
      don_gia: 65000,
      so_luong: 3,
      thanh_tien: 195000,
      topping_snapshot: JSON.stringify([
        { ten: "Thêm pate", gia: 12000, so_luong: 1 },
        { ten: "Thêm xíu", gia: 10000, so_luong: 1 },
      ]),
      ghi_chu: null,
    },
    {
      id_don_hang: orderByCode.get("DH2026032505")!.id,
      id_mon_an: 702,
      ten_mon_snapshot: "Cơm tấm sườn bì chả",
      hinh_anh_snapshot: null,
      don_gia: 65000,
      so_luong: 1,
      thanh_tien: 65000,
      topping_snapshot: null,
      ghi_chu: "Không hành",
    },
    {
      id_don_hang: orderByCode.get("DH2026040707")!.id,
      id_mon_an: context.objectIds.get("mon_an_seed")!,
      ten_mon_snapshot: "Bún bò đặc biệt",
      hinh_anh_snapshot: null,
      don_gia: 59000,
      so_luong: 2,
      thanh_tien: 118000,
      topping_snapshot: JSON.stringify([
        { ten: "Thêm sa tế", gia: 6000, so_luong: 1 },
      ]),
      ghi_chu: "Thêm sa tế riêng",
    },
    {
      id_don_hang: orderByCode.get("DH2026040608")!.id,
      id_mon_an: 702,
      ten_mon_snapshot: "Cơm tấm sườn bì chả",
      hinh_anh_snapshot: null,
      don_gia: 65000,
      so_luong: 2,
      thanh_tien: 130000,
      topping_snapshot: JSON.stringify([
        { ten: "Nước mắm pha", gia: 5000, so_luong: 1 },
      ]),
      ghi_chu: "Thêm nước mắm",
    },
    {
      id_don_hang: orderByCode.get("DH2026032006")!.id,
      id_mon_an: context.objectIds.get("mon_an_seed")!,
      ten_mon_snapshot: "Bún bò đặc biệt",
      hinh_anh_snapshot: null,
      don_gia: 59000,
      so_luong: 2,
      thanh_tien: 118000,
      topping_snapshot: JSON.stringify([
        { ten: "Thêm rau thơm", gia: 3000, so_luong: 1 },
        { ten: "Thêm mắm tôm", gia: 5000, so_luong: 1 },
      ]),
      ghi_chu: null,
    },
  ]);

  await lichSuRepo.save([
    {
      id_don_hang: orderByCode.get("DH2026041101")!.id,
      trang_thai_tu: null,
      trang_thai_den: "cho_xac_nhan",
      noi_dung: "Khách hàng đặt đơn mới",
      id_nguoi_cap_nhat: getUserId(context, "user@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-11T09:15:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026041102")!.id,
      trang_thai_tu: null,
      trang_thai_den: "cho_xac_nhan",
      noi_dung: "Khách hàng đặt đơn mới",
      id_nguoi_cap_nhat: getUserId(context, "creator@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-11T10:05:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026041102")!.id,
      trang_thai_tu: "cho_xac_nhan",
      trang_thai_den: "da_xac_nhan",
      noi_dung: "Cửa hàng xác nhận đơn hàng",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-11T10:08:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026041102")!.id,
      trang_thai_tu: "da_xac_nhan",
      trang_thai_den: "dang_chuan_bi",
      noi_dung: "Cửa hàng đang chuẩn bị món",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-11T10:12:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026041003")!.id,
      trang_thai_tu: null,
      trang_thai_den: "cho_xac_nhan",
      noi_dung: "Khách hàng đặt đơn mới",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-10T19:20:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026041003")!.id,
      trang_thai_tu: "cho_xac_nhan",
      trang_thai_den: "da_xac_nhan",
      noi_dung: "Cửa hàng xác nhận đơn hàng",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-10T19:25:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026041003")!.id,
      trang_thai_tu: "da_xac_nhan",
      trang_thai_den: "dang_giao",
      noi_dung: "Đơn đang được giao",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-10T19:45:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040804")!.id,
      trang_thai_tu: null,
      trang_thai_den: "cho_xac_nhan",
      noi_dung: "Khách hàng đặt đơn mới",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-08T12:10:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040804")!.id,
      trang_thai_tu: "cho_xac_nhan",
      trang_thai_den: "da_xac_nhan",
      noi_dung: "Cửa hàng xác nhận đơn hàng",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-08T12:15:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040804")!.id,
      trang_thai_tu: "da_xac_nhan",
      trang_thai_den: "dang_giao",
      noi_dung: "Đơn đang được giao",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-08T12:45:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040804")!.id,
      trang_thai_tu: "dang_giao",
      trang_thai_den: "da_giao",
      noi_dung: "Đơn hàng đã giao thành công",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-08T13:05:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040707")!.id,
      trang_thai_tu: null,
      trang_thai_den: "cho_xac_nhan",
      noi_dung: "Khách hàng đặt đơn mới",
      id_nguoi_cap_nhat: getUserId(context, "user@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-07T11:00:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040707")!.id,
      trang_thai_tu: "cho_xac_nhan",
      trang_thai_den: "da_xac_nhan",
      noi_dung: "Cửa hàng xác nhận đơn hàng",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-07T11:06:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040707")!.id,
      trang_thai_tu: "da_xac_nhan",
      trang_thai_den: "dang_giao",
      noi_dung: "Đơn đang được giao",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-07T11:35:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040707")!.id,
      trang_thai_tu: "dang_giao",
      trang_thai_den: "da_giao",
      noi_dung: "Đơn hàng đã giao thành công",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-07T11:50:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040608")!.id,
      trang_thai_tu: null,
      trang_thai_den: "cho_xac_nhan",
      noi_dung: "Khách hàng đặt đơn mới",
      id_nguoi_cap_nhat: getUserId(context, "creator@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-06T18:10:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040608")!.id,
      trang_thai_tu: "cho_xac_nhan",
      trang_thai_den: "da_xac_nhan",
      noi_dung: "Cửa hàng xác nhận đơn hàng",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-06T18:15:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040608")!.id,
      trang_thai_tu: "da_xac_nhan",
      trang_thai_den: "dang_giao",
      noi_dung: "Đơn đang được giao",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-06T18:45:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026040608")!.id,
      trang_thai_tu: "dang_giao",
      trang_thai_den: "da_giao",
      noi_dung: "Đơn hàng đã giao thành công",
      id_nguoi_cap_nhat: getUserId(context, "multi@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-04-06T19:00:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026032505")!.id,
      trang_thai_tu: null,
      trang_thai_den: "cho_xac_nhan",
      noi_dung: "Khách hàng đặt đơn mới",
      id_nguoi_cap_nhat: getUserId(context, "user@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-03-25T08:40:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026032505")!.id,
      trang_thai_tu: "cho_xac_nhan",
      trang_thai_den: "da_huy",
      noi_dung: "Khách hàng hủy đơn hàng",
      id_nguoi_cap_nhat: getUserId(context, "user@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-03-25T08:55:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026032006")!.id,
      trang_thai_tu: null,
      trang_thai_den: "cho_xac_nhan",
      noi_dung: "Khách hàng đặt đơn mới",
      id_nguoi_cap_nhat: getUserId(context, "locked@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-03-20T18:30:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026032006")!.id,
      trang_thai_tu: "cho_xac_nhan",
      trang_thai_den: "da_xac_nhan",
      noi_dung: "Cửa hàng xác nhận đơn hàng",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-03-20T18:35:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026032006")!.id,
      trang_thai_tu: "da_xac_nhan",
      trang_thai_den: "dang_giao",
      noi_dung: "Đơn đang được giao",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-03-20T19:00:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026032006")!.id,
      trang_thai_tu: "dang_giao",
      trang_thai_den: "da_giao",
      noi_dung: "Đơn hàng đã giao thành công",
      id_nguoi_cap_nhat: getUserId(context, "store@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-03-20T19:25:00"),
    },
    {
      id_don_hang: orderByCode.get("DH2026032006")!.id,
      trang_thai_tu: "da_giao",
      trang_thai_den: "tra_hang",
      noi_dung: "Khách hàng gửi yêu cầu trả hàng",
      id_nguoi_cap_nhat: getUserId(context, "locked@dishnet.vn")!,
      thoi_gian_cap_nhat: new Date("2026-03-20T20:05:00"),
    },
  ]);
}
